export { About } from './about'
export { Contact } from './contact'
export { Footer } from './footer'
export { Header } from './header'
export { Hero } from './hero'
export { Reviews } from './reviews'
export { Services } from './services'
export { WhatsAppFloat } from './whatsapp-float'
